title:              Ian Goodrich
email:              goodrichian@gmail.com
description:        Code, research and funding for non-profits
author:             Ian Goodrich
root: /
baseurl: /
url:                "https://specialprocedures.github.io"

# Set encoding
encoding: utf-8

# Social Profiles
twitter_username:   
github_username:    specialprocedures
facebook_username:  
instagram_username:  
linkedin_username:  igdrch

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
